### ISSUE TITLE
Hardcoded name in the profile menu

### ISSUE THREAD

**Issue by vivek-singh-13** [imhardikdesai/E-Commerce-Managment#2]
I have noticed that after logging in by an account, your name 'Hardik Desai' shows up in the profile menu instead of the user's name. Also the profile picture is your's. I can try to fix this if you assign this issue.

**Comment by imhardikdesai** [comment]
Sure please start working on it. I will assign you

**Comment by vivek-singh-13** [comment]
I have updated the Profile name but not the image (image attached for reference). The name is not hardcoded now, it is the current user's name. If you want me to change the image to a profile icon image then I will do it otherwise I will push the current changed code.  
![image](https://github.com/imhardikdesai/E-Commerce-Managment/assets/78148430/d8febbed-df49-4bea-8115-f55ab3ed28b6)

**Comment by imhardikdesai** [comment]
Yea please use profile icon

**Comment by vivek-singh-13** [comment]
I created a pull request for the same, check how is it now.
![image](https://github.com/imhardikdesai/E-Commerce-Managment/assets/78148430/d885dcc4-f612-4fe1-a202-cd9bace14570)
